# Generated by Django 6.0.6 on 2026-06-17 21:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_alter_category_title_alter_menuitem_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='menu_items',
            new_name='menuitems',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='unitprice',
            new_name='unit_price',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'menuitems')},
        ),
    ]
